// <auto-generated />
namespace Gestion_d_ecole.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class changement_des_listes_à_collection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changement_des_listes_à_collection));
        
        string IMigrationMetadata.Id
        {
            get { return "202502271214228_changement_des_listes_à_collection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
