// <auto-generated />
namespace Gestion_d_ecole.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class creation_des_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creation_des_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202502262252036_creation_des_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
